# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polygonx.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'polygonx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epolygonx.proto\x12\x08polygonx\"\x8a\x01\n\x08RawProto\x12\x0e\n\x06method\x18\x01 \x01(\x05\x12\r\n\x05proto\x18\x02 \x01(\x0c\x12\x0f\n\x07request\x18\x03 \x01(\x0c\x12\x11\n\ttrainerId\x18\x04 \x01(\t\x12\x14\n\x0ctrainerLevel\x18\x05 \x01(\x05\x12%\n\x1dhas_geotargeted_ar_scan_quest\x18\x06 \x01(\x08\"\x84\x01\n\x13RawPushGatewayProto\x12\x0e\n\x06method\x18\x01 \x01(\x05\x12\r\n\x05proto\x18\x02 \x01(\x0c\x12\x11\n\ttrainerId\x18\x04 \x01(\t\x12\x14\n\x0ctrainerLevel\x18\x05 \x01(\x05\x12%\n\x1dhas_geotargeted_ar_scan_quest\x18\x06 \x01(\x08\"{\n\x19RawProtoCollectionMessage\x12\"\n\x06protos\x18\x01 \x03(\x0b\x32\x12.polygonx.RawProto\x12:\n\x13push_gateway_protos\x18\x02 \x03(\x0b\x32\x1d.polygonx.RawPushGatewayProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polygonx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWPROTO']._serialized_start=29
  _globals['_RAWPROTO']._serialized_end=167
  _globals['_RAWPUSHGATEWAYPROTO']._serialized_start=170
  _globals['_RAWPUSHGATEWAYPROTO']._serialized_end=302
  _globals['_RAWPROTOCOLLECTIONMESSAGE']._serialized_start=304
  _globals['_RAWPROTOCOLLECTIONMESSAGE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
