"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class RawProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    METHOD_FIELD_NUMBER: builtins.int
    PROTO_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    TRAINERID_FIELD_NUMBER: builtins.int
    TRAINERLEVEL_FIELD_NUMBER: builtins.int
    HAS_GEOTARGETED_AR_SCAN_QUEST_FIELD_NUMBER: builtins.int
    method: builtins.int = ...
    proto: builtins.bytes = ...
    request: builtins.bytes = ...
    trainerId: typing.Text = ...
    trainerLevel: builtins.int = ...
    has_geotargeted_ar_scan_quest: builtins.bool = ...
    def __init__(self,
        *,
        method : builtins.int = ...,
        proto : builtins.bytes = ...,
        request : builtins.bytes = ...,
        trainerId : typing.Text = ...,
        trainerLevel : builtins.int = ...,
        has_geotargeted_ar_scan_quest : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["has_geotargeted_ar_scan_quest",b"has_geotargeted_ar_scan_quest","method",b"method","proto",b"proto","request",b"request","trainerId",b"trainerId","trainerLevel",b"trainerLevel"]) -> None: ...
global___RawProto = RawProto

class RawPushGatewayProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    METHOD_FIELD_NUMBER: builtins.int
    PROTO_FIELD_NUMBER: builtins.int
    TRAINERID_FIELD_NUMBER: builtins.int
    TRAINERLEVEL_FIELD_NUMBER: builtins.int
    HAS_GEOTARGETED_AR_SCAN_QUEST_FIELD_NUMBER: builtins.int
    method: builtins.int = ...
    proto: builtins.bytes = ...
    trainerId: typing.Text = ...
    trainerLevel: builtins.int = ...
    has_geotargeted_ar_scan_quest: builtins.bool = ...
    def __init__(self,
        *,
        method : builtins.int = ...,
        proto : builtins.bytes = ...,
        trainerId : typing.Text = ...,
        trainerLevel : builtins.int = ...,
        has_geotargeted_ar_scan_quest : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["has_geotargeted_ar_scan_quest",b"has_geotargeted_ar_scan_quest","method",b"method","proto",b"proto","trainerId",b"trainerId","trainerLevel",b"trainerLevel"]) -> None: ...
global___RawPushGatewayProto = RawPushGatewayProto

class RawProtoCollectionMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PROTOS_FIELD_NUMBER: builtins.int
    PUSH_GATEWAY_PROTOS_FIELD_NUMBER: builtins.int
    @property
    def protos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RawProto]: ...
    @property
    def push_gateway_protos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RawPushGatewayProto]: ...
    def __init__(self,
        *,
        protos : typing.Optional[typing.Iterable[global___RawProto]] = ...,
        push_gateway_protos : typing.Optional[typing.Iterable[global___RawPushGatewayProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["protos",b"protos","push_gateway_protos",b"push_gateway_protos"]) -> None: ...
global___RawProtoCollectionMessage = RawProtoCollectionMessage
